---
- name: Create a list of WordPress plugins
  hosts: "{{ node }}"
  vars_files: defaults/main.yaml
  gather_facts: false
  ignore_errors: true
  tasks:
    - name: Build a complete list of plugins organzied by site
      tags: granular
      block:
        - name: Compile the per site plugin list
          ansible.builtin.script:
            cmd: "{{ GIT }}report.rb {{ path }} active"

        - name: Fix empty Plugin field at bcgov-opengraph
          ansible.builtin.replace:
            path: site-active-plugins.yaml
            regexp: "  - Plugin: bcgov-opengraph\n    Version: "
            replace: "  - Plugin: bcgov-opengraph\n    Version: 1.8.0"
            mode: '0644'

        - name: Download the site-active-plugins.yaml file
          ansible.builtin.fetch:
            src: plugins/site-active-plugins.yaml
            dest: "{{ GIT }}results/"
            flat: true
            mode: '0644'

    - name: Build a complete list of plugins at the domain level
      tags: single
      block:
        - name: Compile the domain level plugin list
          ansible.builtin.script:
            cmd: "{{ GIT }list.rb {{ path }} active"

        - name: Filter out duplicates from domain-unfiltered-active-plugins.txt
          ansible.builtin.script:
            cmd: "{{ GIT }uniq.rb plugins/domain-unfiltered-active-plugins.txt plugins/active-plugins-list.txt"

        - name: Download the active-plugins-list file
          ansible.builtin.fetch:
            src: plugins/active-plugins-list.txt
            dest: "{{ GIT }}results/"
            flat: true
            mode: '0644'

    - name: Build a complete list of plugins and their version at the domain level
      tags: combo
      block:
        - name: Compile the domain level plugin/version list
          ansible.builtin.script:
            cmd: "{{ GIT }make.rb active"

        - name: Download the domain-active-plugins file
          ansible.builtin.fetch:
            src: plugins/domain-active-plugins.yaml
            dest: "{{ GIT }}results/"
            flat: true
            mode: '0644'
...